### ISSUE TITLE
Offering to adopt this repo

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-localize#73]
Hi @lfabreges, if you want to permanently move this repo to a new owner, then I'm volunteering to adopt this repo. I will still depend on external contributors, but I do have time to do a little maintenance. If you're OK with it, please move it to my account. In the past you've already added me as a (co)owner to the npm package, so that's already settled 😉

Thanks for creating and maintaining this repo!

**Comment by lfabreges** [comment]
Hi, fine with me

**Comment by lfabreges** [comment]
@EddyVerbruggen You need to remove your own nativescript-localize repository before, tell me when it's done and I'll transfer this one to you

**Comment by EddyVerbruggen** [comment]
@lfabreges Thanks mate! I've now removed my fork, so please try again.

**Comment by abhayastudios** [comment]
@EddyVerbruggen thanks for adopting this plugin! Very reassuring it continues to be in good hands :)

**Comment by alsonLee-BeckTaxi** [comment]
Hi 
Will there soon be a version that works with the later version of Angular.
As I found out it can't work with any Angular version that uses Ivy; which anything beyond Angular 8 won't work

Let me know, 
thank you in advance
