### ISSUE TITLE
GitHub reported vulnerabilities ?

### ISSUE THREAD

**Issue by MopheusDG** [EddyVerbruggen/nativescript-localize#76]
Hi @EddyVerbruggen nice to see this plugin will stay alive. Just one question, when the repo was on @lfabreges he said that github has reported some vulnerabilites in certain dependencies. Do you know what was that about ?

Thanks.

**Comment by EddyVerbruggen** [comment]
Hi, Github reports any security-related issues it finds in `package-lock.json` and will report that privately to the repo owner.

The offending dependencies have now been updated to newer versions, meaning those high and critical security issues are now gone.
