### ISSUE TITLE
Deprecated in description of github repo

### ISSUE THREAD

**Issue by CoreyKaylor** [EddyVerbruggen/nativescript-localize#82]
Might be good to take the deprecation out of the description in the github repo. Definitely might give off the wrong impression when there's clearly progress being made.

**Comment by AlexBa** [comment]
Thought the same. I was a little bit confused^^

**Comment by maxorlovsky** [comment]
@EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Cheers guys, removed that bit.
