### ISSUE TITLE
Please Upgrade Plugin to Naticescript 7 and Angular 10

### ISSUE THREAD

**Issue by cjohn001** [EddyVerbruggen/nativescript-localize#99]

**Comment by NathanWalker** [comment]
@EddyVerbruggen We can add this one to https://github.com/NativeScript/plugins and have an update scoped and out by Friday if that works for you.

**Comment by EddyVerbruggen** [comment]
@NathanWalker Yes, that's perfectly fine by me!

**Comment by NathanWalker** [comment]
@nativescript/localize 5.0.x published with {N} 7 compatibility now.

**Comment by pandabamboo90** [comment]
@NathanWalker Can you please guide me how to add localize 5.0.x in the project ?

I put `"nativescript-localize": "~5.0.0` in `package.json` then try `npm install`, but it said cannot find the npm package

Thanks.

**Comment by EddyVerbruggen** [comment]
@pandabamboo90 Look closely: `"@nativescript/localize": "~5.0.2"`

**Comment by pandabamboo90** [comment]
@EddyVerbruggen Thanks.

I changed `"nativescript-localize": "~5.0.0"` -> `"@nativescript/localize": "~5.0.2"`.

Everything is working now 👍
